#!/system/bin/sh

BB=/system/bin/busybox

# Mounting #

$BB mount -o remount,rw /
$BB mount -o remount,rw / /
$BB mount -o remount,rw rootfs
$BB mount -o remount,rw /system
$BB mount -o remount,rw /system /system

# Better Scrolling #
BS=/data/tweakslog/06BSC.log
if [ -e $BS ]; then
	rm $BS;
fi;
chown 0:0 -R /data/tweakslog/06BSC.log
chmod 755 -R /data/tweakslog/06BSC.log
chcon u:object_r:system_data_file:s0 /data/tweakslog/06BSC.log
$BB echo "" | $BB tee -a $BS;
$BB echo "Better Scrolling started on : $( date +"%m-%d-%Y %H:%M:%S" ) " | $BB tee -a $BS;
if [ -e /sys/module/tpd_setting/parameters/tpd_mode ]; then
$BB echo "1" > /sys/module/tpd_setting/parameters/tpd_mode
fi;
if [ -e /sys/module/hid_magicmouse/parameters/scroll_speed ]; then
$BB echo "63" > /sys/module/hid_magicmouse/parameters/scroll_speed
fi;
$BB echo "=>Mod in /sys/module/tpd_setting/parameters/tpd_mode" | $BB tee -a $BS;
$BB echo "=>Mod in /sys/module/hid_magicmouse/parameters/scroll_speed" | $BB tee -a $BS;
$BB echo "Better Scrolling Configured" | $BB tee -a $BS;
$BB echo "Better Scrolling completed at  : $( date +"%m-%d-%Y %H:%M:%S" ) " | $BB tee -a $BS;

# Set Permissions

chown 0:0 -R /data/tweakslog/06BSC.log
chmod 755 -R /data/tweakslog/06BSC.log
chcon u:object_r:system_data_file:s0 /data/tweakslog/06BSC.log

# Remount read-only
$BB mount -o remount,ro /
$BB mount -o remount,ro / /
$BB mount -o remount,ro rootfs
$BB mount -o remount,ro /system
$BB mount -o remount,ro /system /system